import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';
import { collectTokenRecords, loadTokenSources } from './token-model.mjs';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const packageDir = path.resolve(__dirname, '..');
const distDir = path.join(packageDir, 'dist');

const { primitive, semantic, density, theme } = loadTokenSources(packageDir);
const registry = primitive;
const semanticTree = semantic;
const densityTrees = density;
const themeTrees = theme;

function semanticRecords(tokenTree) {
  return collectTokenRecords(tokenTree, registry).filter((record) => record.path.startsWith('pd.'));
}

const defaultDensity = densityTrees.default;
const darkTheme = themeTrees.dark;

function transformValue(record) {
  switch (record.type) {
    case 'color':
      return record.value.hex;
    case 'dimension':
      return `${record.value.value}${record.value.unit}`;
    case 'duration':
      return `${record.value.value}${record.value.unit}`;
    case 'cubicBezier':
      return `cubic-bezier(${record.value.join(', ')})`;
    case 'fontWeight':
      return String(record.value);
    case 'number':
      return String(record.value);
    case 'fontFamily':
      return record.value.join(', ');
    case 'typography':
      return [
        `${record.value.fontFamily.join(', ')}`,
        `${record.value.fontSize.value}${record.value.fontSize.unit}`,
        `font-weight ${record.value.fontWeight}`,
        `line-height ${record.value.lineHeight}`,
        `letter-spacing ${record.value.letterSpacing.value}${record.value.letterSpacing.unit}`
      ].join(' ');
    default:
      throw new Error(`Unsupported token type "${record.type}" at "${record.path}".`);
  }
}

function cssVariableName(tokenPath) {
  return `--${tokenPath.split('.').join('-')}`;
}

function renderCssBlock(selector, records) {
  const lines = [`${selector} {`];
  for (const record of records) {
    lines.push(`  ${cssVariableName(record.path)}: ${transformValue(record)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function renderCss() {
  const themeSelector = ':root[data-theme="dark"]';
  const densitySelector = ':root[data-density]';
  const baseSemanticRecords = semanticRecords(semanticTree).filter((record) => !record.path.startsWith('pd.color.'));
  const themeRecords = semanticRecords(themeTrees.dark);
  const densityRecords = {
    compact: semanticRecords(densityTrees.compact),
    default: semanticRecords(densityTrees.default),
    spacious: semanticRecords(densityTrees.spacious)
  };

  const defaultDensityBlock = renderCssBlock(densitySelector, densityRecords.default);
  const compactBlock = renderCssBlock(':root[data-density="compact"]', densityRecords.compact);
  const spaciousBlock = renderCssBlock(':root[data-density="spacious"]', densityRecords.spacious);
  const themeBlock = renderCssBlock(themeSelector, themeRecords);
  const semanticBlock = renderCssBlock(':root', baseSemanticRecords);

  return [
    '/* Generated by Palladio Style Dictionary pipeline. Do not edit. */',
    '',
    semanticBlock,
    '',
    themeBlock,
    '',
    defaultDensityBlock,
    '',
    compactBlock,
    '',
    spaciousBlock,
    ''
  ].join('\n');
}

function nestedObject(records) {
  const object = {};
  for (const record of records) {
    const parts = record.path.split('.').slice(1);
    let current = object;
    while (parts.length > 1) {
      const key = parts.shift();
      if (!Object.hasOwn(current, key)) current[key] = {};
      current = current[key];
    }
    current[parts[0]] = record.value;
  }
  return object;
}

function stableStringify(value, indentation = 2) {
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item, indentation)).join(', ')}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    return entries.length === 0
      ? '{}'
      : `{\n${entries.map(([key, item]) => `${' '.repeat(indentation)}${JSON.stringify(key)}: ${stableStringify(item, indentation + 2)}`).join(',\n')}\n${' '.repeat(indentation - 2)}}`;
  }
  return JSON.stringify(value);
}

function renderTs() {
  const semantic = nestedObject(semanticRecords(semanticTree));
  const densities = {
    compact: nestedObject(semanticRecords(densityTrees.compact)),
    default: nestedObject(semanticRecords(densityTrees.default)),
    spacious: nestedObject(semanticRecords(densityTrees.spacious))
  };
  const theme = { dark: nestedObject(semanticRecords(themeTrees.dark)) };

  return [
    '// Generated by Palladio Style Dictionary pipeline. Do not edit.',
    '',
    `export const palladioTokens = ${stableStringify(semantic)} as const;`,
    `export const palladioDensity = ${stableStringify(densities)} as const;`,
    `export const palladioTheme = ${stableStringify(theme)} as const;`,
    '',
    'export type PalladioTokenValue =',
    '  | string',
    '  | number',
    '  | readonly string[]',
    '  | { readonly value: number; readonly unit: string }',
    '  | readonly [number, number, number, number];',
    ''
  ].join('\n');
}

function renderJson() {
  return `${JSON.stringify({
    semantic: nestedObject(semanticRecords(semanticTree)),
    density: {
      compact: nestedObject(semanticRecords(densityTrees.compact)),
      default: nestedObject(semanticRecords(densityTrees.default)),
      spacious: nestedObject(semanticRecords(densityTrees.spacious))
    },
    theme: { dark: nestedObject(semanticRecords(themeTrees.dark)) }
  }, null, 2)}\n`;
}

function ensureDirectory(directory) {
  fs.mkdirSync(directory, { recursive: true });
}

function writeGeneratedFile(relativePath, content) {
  const target = path.join(distDir, relativePath);
  ensureDirectory(path.dirname(target));
  fs.writeFileSync(target, content, 'utf8');
}

export async function run() {
  writeGeneratedFile(path.join('css', 'palladio.css'), renderCss());
  writeGeneratedFile(path.join('ts', 'tokens.ts'), renderTs());
  writeGeneratedFile(path.join('json', 'tokens.json'), renderJson());
  console.log('Generated CSS, TypeScript and JSON artifacts.');
}

await run();
