import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { loadTokenSources } from './token-model.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(__dirname, '..');
const distDir = path.join(packageDir, 'dist');

const { primitive, semantic, density, theme } = loadTokenSources(packageDir);

// Keep primitive tokens available to Style Dictionary for reference resolution,
// while putting each public token set under its artifact namespace.
const tokens = {
  ...primitive,
  semantic: semantic.pd,
  density: {
    compact: density.compact.pd,
    default: density.default.pd,
    spacious: density.spacious.pd
  },
  theme: { dark: theme.dark.pd }
};

function tokenValue(token) {
  return token['$value'];
}

function tokenType(token) {
  return token['$type'];
}

function transformCssValue(token) {
  const value = tokenValue(token);
  switch (tokenType(token)) {
    case 'color':
      return value.hex;
    case 'dimension':
    case 'duration':
      return `${value.value}${value.unit}`;
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'fontWeight':
    case 'number':
      return String(value);
    case 'fontFamily':
      return value.join(', ');
    case 'typography':
      return [
        `${value.fontFamily.join(', ')}`,
        `${value.fontSize.value}${value.fontSize.unit}`,
        `font-weight ${value.fontWeight}`,
        `line-height ${value.lineHeight}`,
        `letter-spacing ${value.letterSpacing.value}${value.letterSpacing.unit}`
      ].join(' ');
    default:
      throw new Error(`Unsupported token type "${tokenType(token)}" at "${token.key}".`);
  }
}

function cssVariableName(token) {
  const pathStart = token.path[0] === 'semantic' ? 1 : 2;
  return `--pd-${token.path.slice(pathStart).join('-')}`;
}

function cssBlock(selector, records) {
  const lines = [`${selector} {`];
  for (const record of records) {
    lines.push(`  ${cssVariableName(record)}: ${transformCssValue(record)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function renderCss({ dictionary }) {
  const records = dictionary.allTokens;
  const semanticRecords = records.filter(
    (token) => token.path[0] === 'semantic' && token.path[1] !== 'color'
  );
  const themeRecords = records.filter(
    (token) => token.path[0] === 'theme' && token.path[1] === 'dark'
  );
  const densityRecords = (name) => records.filter(
    (token) => token.path[0] === 'density' && token.path[1] === name
  );

  return [
    '/* Generated by Palladio Style Dictionary pipeline. Do not edit. */',
    '',
    cssBlock(':root', semanticRecords),
    '',
    cssBlock(':root[data-theme="dark"]', themeRecords),
    '',
    cssBlock(':root[data-density]', densityRecords('default')),
    '',
    cssBlock(':root[data-density="compact"]', densityRecords('compact')),
    '',
    cssBlock(':root[data-density="spacious"]', densityRecords('spacious')),
    ''
  ].join('\n');
}

function nestedValues(records, stripSegments) {
  const result = {};
  for (const record of records) {
    const parts = record.path.slice(stripSegments);
    let current = result;
    for (const key of parts.slice(0, -1)) {
      if (!Object.hasOwn(current, key)) current[key] = {};
      current = current[key];
    }
    current[parts.at(-1)] = tokenValue(record);
  }
  return result;
}

function tokenSets(dictionary) {
  const records = dictionary.allTokens;
  const semanticRecords = records.filter((token) => token.path[0] === 'semantic');
  const densityRecords = (name) => records.filter(
    (token) => token.path[0] === 'density' && token.path[1] === name
  );
  const themeRecords = records.filter(
    (token) => token.path[0] === 'theme' && token.path[1] === 'dark'
  );

  return {
    semantic: nestedValues(semanticRecords, 1),
    density: {
      compact: nestedValues(densityRecords('compact'), 2),
      default: nestedValues(densityRecords('default'), 2),
      spacious: nestedValues(densityRecords('spacious'), 2)
    },
    theme: { dark: nestedValues(themeRecords, 2) }
  };
}

function stableStringify(value, indentation = 2) {
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item, indentation)).join(', ')}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    return entries.length === 0
      ? '{}'
      : `{
${entries.map(([key, item]) => `${' '.repeat(indentation)}${JSON.stringify(key)}: ${stableStringify(item, indentation + 2)}`).join(',\n')}
${' '.repeat(indentation - 2)}}`;
  }
  return JSON.stringify(value);
}

function renderTs({ dictionary }) {
  const { semantic, density, theme } = tokenSets(dictionary);
  return [
    '// Generated by Palladio Style Dictionary pipeline. Do not edit.',
    '',
    `export const palladioTokens = ${stableStringify(semantic)} as const;`,
    `export const palladioDensity = ${stableStringify(density)} as const;`,
    `export const palladioTheme = ${stableStringify(theme)} as const;`,
    '',
    'export type PalladioTokenValue =',
    '  | string',
    '  | number',
    '  | readonly string[]',
    '  | { readonly value: number; readonly unit: string }',
    '  | readonly [number, number, number, number];',
    ''
  ].join('\n');
}

function renderJson({ dictionary }) {
  return `${JSON.stringify(tokenSets(dictionary), null, 2)}\n`;
}

// ---------------------------------------------------------------------------
// agent-reference.md — Spec 9.3–9.4 core deliverable. Generated from the same
// token records as CSS/TS/JSON so the four artifacts can never drift apart.
// Everything table-shaped below is pulled from dictionary.allTokens; the
// prose (role, usage rules, prohibitions) is static policy text sourced from
// docs/spec.md chapters 1–8 and palladio/docs/accessibility/accessibility-contract.md.
// ---------------------------------------------------------------------------

function escapeCell(value) {
  return String(value).replace(/\|/g, '\\|');
}

function mdTable(headers, rows) {
  const headerLine = `| ${headers.join(' | ')} |`;
  const dividerLine = `| ${headers.map(() => '---').join(' | ')} |`;
  const bodyLines = rows.map((row) => `| ${row.map(escapeCell).join(' | ')} |`);
  return [headerLine, dividerLine, ...bodyLines].join('\n');
}

// Some semantic token sources describe a value the table already shows in its
// own "Value" column (e.g. a space token's $description is literally "4px",
// or a radius token's ends in " (4px)"). Strip that duplication for display —
// this only touches the generated Markdown, never the token source files.
function cleanDescription(record) {
  const raw = record['$description'] ?? '';
  const value = transformCssValue(record);
  if (raw.trim() === value) return '—';
  const duplicateSuffix = new RegExp(`\\s*\\(${value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&')}\\)\\s*$`);
  const cleaned = raw.replace(duplicateSuffix, '').trim();
  return cleaned.length > 0 ? cleaned : '—';
}

function colorGroup(records, predicate) {
  return records
    .filter((record) => predicate(record.path[2]))
    .map((record) => [`\`${cssVariableName(record)}\``, transformCssValue(record), cleanDescription(record)]);
}

function typographyRows(records) {
  return records.map((record) => {
    const value = tokenValue(record);
    return [
      `\`${cssVariableName(record)}\``,
      value.fontFamily[0],
      `${value.fontSize.value}${value.fontSize.unit}`,
      String(value.fontWeight),
      String(value.lineHeight),
      `${value.letterSpacing.value}${value.letterSpacing.unit}`,
      cleanDescription(record)
    ];
  });
}

function scalarRows(records) {
  return records.map((record) => [`\`${cssVariableName(record)}\``, transformCssValue(record), cleanDescription(record)]);
}

function densityLookup(records, name) {
  const map = new Map();
  for (const record of records.filter((r) => r.path[0] === 'density' && r.path[1] === name)) {
    map.set(record.path.slice(2).join('.'), transformCssValue(record));
  }
  return map;
}

function renderAgentReference({ dictionary }) {
  const records = dictionary.allTokens;
  const colorRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'color');
  const textRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'text');
  const spaceRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'space');
  const radiusRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'radius');
  const durationRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'duration');
  const easingRecords = records.filter((t) => t.path[0] === 'semantic' && t.path[1] === 'easing');

  const densityNames = ['compact', 'default', 'spacious'];
  const densityMaps = Object.fromEntries(densityNames.map((name) => [name, densityLookup(records, name)]));
  const densityRows = [
    ['Base spacing unit', 'density.base.spacing-unit'],
    ['Component padding — vertical', 'density.component.padding.vertical'],
    ['Component padding — horizontal', 'density.component.padding.horizontal'],
    ['Min interactive size (A-M6)', 'density.component.min-interactive-size'],
    ['Body font size', 'density.typography.body-font-size']
  ].map(([label, key]) => [label, ...densityNames.map((name) => densityMaps[name].get(key))]);

  return `# Palladio Agent Reference

> Generated by Palladio Style Dictionary pipeline. Do not edit by hand — run \`npm run rebuild\`.
> Spec 路徑：\`docs/spec.md\`（對應章節 9.3–9.4, 13）／可及性契約：\`palladio/docs/accessibility/accessibility-contract.md\`

## 這份文件是給誰的

當 AI 代理（Claude Code、Codex 等）收到「用 Palladio，某 density」的指令時，這份文件把設計決策的搜索空間從「無限色值／間距／動效」縮小到下面表格列出的**有限選項**。所有值都直接來自 token 來源，與 \`dist/css/palladio.css\`、\`dist/ts/tokens.ts\`、\`dist/json/tokens.json\` 保證一致——改動任何 token 只需要重跑 pipeline，不需要手動同步這份文件。

單次 AI 生成的表現只是設計語言的質性訊號，不是完成 gate（規格 9.4）；本文件的職責是提供正確的約束，不是保證生成結果。

---

## 一、使用規則

1. **三層架構**：元件只能引用 Semantic（下表）或可選的 Component 層 token；**不得**直接引用 Primitive 值（例如某個 hex 色碼或裸的 px 數字），即使它剛好等於某個 Semantic token 的值。
2. **命名空間**：CSS 自訂屬性一律 \`--pd-{role}\`；TypeScript 透過 \`palladioTokens\` / \`palladioDensity\` / \`palladioTheme\`（\`dist/ts/tokens.ts\`）取用；Go／其他消費端讀 \`dist/json/tokens.json\`（\`semantic\` / \`density\` / \`theme\` 三個頂層 key）。
3. **Density 切換**：透過 \`data-density="compact"\` / \`data-density="spacious"\`（省略時為 Default）套用在容器上；元件結構本身不因 density 改變，只有 padding、最小互動尺寸與 body 字級跟著換。
4. **Theme**：目前只有暗色主題，選擇器為 \`:root[data-theme="dark"]\`；Light theme 補齊前不要假設有其他主題存在。
5. **Accent 插槽是產品責任**：見第三節，Palladio 本身不提供 accent 色值。
6. **Motion**：一般狀態使用 \`pd-duration-*\` 搭配 \`pd-easing-*\`；\`prefers-reduced-motion: reduce\` 觸發時的行為是唯一、已定案的契約（見第五節），不是自由發揮空間。
7. **可及性 MUST 規則（A-M1–A-M6）不是建議**，是每個元件驗收都要過的硬門檻，摘要見第五節，完整驗證方式見 \`accessibility-contract.md\`。

## 二、禁止事項

- **不得將 Primitive token 直接用於 UI 元件**——所有 UI 樣式只能引用下面的 Semantic 表格。
- **不得為 accent 插槽加入 fallback、推導色值，或跨消費端的混色公式**——缺哪個插槽就是缺，不得用其他插槽湊。
- **不得放寬任何 A-M1–A-M6 的 MUST 門檻**（例如把 4.5:1 降成 4:1，或幫某個元件開特例）。
- **不得只用色彩傳達資訊或狀態**（A-M5）——語意色需搭配文字、圖示或其他非色彩線索。
- **不得使用 font-weight 100–300**（規格 3.3，深色背景上過細難以閱讀）。
- **不得用 \`outline: none\` 移除 focus 樣式卻不提供替代的可見 focus indicator**（A-M3）。
- **不得預設把 \`pd-color-border-strong\` 當作 focus ring 唯一依據**——它對系統現有表面對比皆低於 A-M2 的 3:1（已確認缺漏，追蹤於 [Issue #21](https://github.com/bext1998/palladio-design-language-system/issues/21)），元件必須自行選一個能驗證通過 3:1 的呈現方式（例如產品 accent 色、\`text-primary\`，或雙層 ring），見 \`accessibility-contract.md\` 第四節。

## 三、色彩

### 表面層級

${mdTable(['Token', 'Value', '用途'], colorGroup(colorRecords, (name) => name === 'bg' || name.startsWith('surface')))}

### 線條與分隔

${mdTable(['Token', 'Value', '用途'], colorGroup(colorRecords, (name) => name.startsWith('border')))}

### 文字層級

${mdTable(['Token', 'Value', '用途'], colorGroup(colorRecords, (name) => name.startsWith('text')))}

### 語意色（success / warning / danger / info）

${mdTable(['Token', 'Value', '用途'], colorGroup(colorRecords, (name) => ['success', 'warning', 'danger', 'info'].includes(name)))}

> 語意色與上列所有文字色，在四層表面上皆已驗證達 A-M1（≥4.5:1），見 \`accessibility-contract.md\` 第二節。

### Accent 插槽（各產品自行提供，Palladio 不定義值）

| Token | 說明 | 值 |
|---|---|---|
| \`--pd-color-accent\` | 主強調色 | *由產品提供* |
| \`--pd-color-accent-hover\` | hover 狀態 | *由產品提供* |
| \`--pd-color-accent-active\` | active 狀態 | *由產品提供* |
| \`--pd-color-accent-disabled\` | disabled 狀態 | *由產品提供* |
| \`--pd-color-accent-subtle\` | 低飽和背景（badge、tag 底色） | *由產品提供* |
| \`--pd-color-accent-text\` | 強調色上的文字 | *由產品提供* |

產品必須提供全部六個插槽；\`accent-text\` 對 \`accent\` / \`accent-hover\` / \`accent-active\` / \`accent-disabled\` 四種背景須驗證 ≥4.5:1（A-M1），其餘實際使用的配對依內容判定 A-M1 或 A-M2。完整流程見 \`accessibility-contract.md\` 第九節；驗證函式骨架見 \`palladio/pipeline/validate-accessibility.mjs\` 的 \`validateAccentPairs()\`。

---

## 四、字體

${mdTable(['Token', 'Font', 'Size', 'Weight', 'Line-height', 'Letter-spacing', '用途'], typographyRows(textRecords))}

> \`--pd-text-*\` 的 CSS 值是描述性組合字串（非標準 \`font\` shorthand），元件實作請個別讀取上表的 Size／Weight／Line-height／Letter-spacing 欄位，或改用 TS／JSON 產物中對應的結構化欄位（\`fontSize\`、\`fontWeight\`、\`lineHeight\`、\`letterSpacing\`）。

## 五、形狀、間距與動效

### 圓角

${mdTable(['Token', 'Value', '用途'], scalarRows(radiusRecords))}

### 間距（4px 基礎單位）

${mdTable(['Token', 'Value', '用途'], scalarRows(spaceRecords))}

> \`pd-space-{n}\` 的 \`n\` 就是 4px 的倍數（\`space-3\` = 3 × 4px = 12px）。所有間距必須是 4 的倍數。

### Duration

${mdTable(['Token', 'Value', '用途'], scalarRows(durationRecords))}

### Easing

${mdTable(['Token', 'Value', '用途'], scalarRows(easingRecords))}

### Reduced Motion 契約（唯一、已定案，見 accessibility-contract.md 第六節）

| 情境 | 一般 | \`prefers-reduced-motion: reduce\` |
|---|---|---|
| Transform 類動畫 | 依 \`pd-duration-*\` / \`pd-easing-*\` 正常播放 | **完全移除**，不套用任何 transition／animation |
| 必要保留的 opacity 狀態切換 | 正常過渡 | **瞬時切換**（\`pd-duration-instant\` / \`0ms\`），不保留 transition |
| 非必要裝飾性動畫 | 正常播放 | 直接停用 |

---

## 六、Density Preset

${mdTable(['項目', 'Compact', 'Default', 'Spacious'], densityRows)}

套用方式：容器加上 \`data-density="compact"\` 或 \`data-density="spacious"\`；省略時套用 Default（\`:root[data-density]\` 選擇器提供 fallback）。三種 density 下元件結構保持不變，只有上表五個值跟著切換。

---

## 七、可及性 MUST 規則摘要（A-M1–A-M6）

| 規則 | 摘要 | 門檻 |
|---|---|---|
| A-M1 | 一般文字（含 placeholder、disabled）對比 | ≥ 4.5:1 |
| A-M2 | 大字（≥24px regular / ≥18.5px bold）與 UI 元件對比 | ≥ 3:1 |
| A-M3 | 所有互動元件需有可見 focus indicator | 不得僅 \`outline: none\` 無替代 |
| A-M4 | \`prefers-reduced-motion\` 觸發時停用非必要動畫 | 見第五節契約 |
| A-M5 | 色彩不可為唯一資訊傳達手段 | 需搭配非色彩線索 |
| A-M6 | 互動元素最小尺寸依 density | 32 / 36 / 48px（見第六節） |

完整驗收說明、對比計算結果與已確認缺漏（含 \`border-strong\` focus ring 問題）見 \`palladio/docs/accessibility/accessibility-contract.md\`；可用 \`npm run validate:tokens\` 與 \`npm run validate:accessibility\` 重新驗證。

---

## 八、消費範例

\`\`\`css
.card {
  background: var(--pd-color-surface-raised);
  border: 1px solid var(--pd-color-border-subtle);
  border-radius: var(--pd-radius-md);
  padding: var(--pd-space-4);
}
\`\`\`

\`\`\`ts
import { palladioTokens, palladioDensity } from '@palladio/design-system/dist/ts/tokens';

const bg = palladioTokens.color.surface.hex;
const compactPadding = palladioDensity.compact.density.component.padding;
\`\`\`

\`\`\`json
// dist/json/tokens.json
{ "semantic": { "color": { "bg": { "hex": "#141414" } } } }
\`\`\`
`;
}

const styleDictionary = new StyleDictionary({
  tokens,
  hooks: {
    transforms: {
      'name/palladio': {
        type: 'name',
        transform: (token) => token.path.join('-')
      }
    },
    formats: {
      'palladio/css': renderCss,
      'palladio/typescript': renderTs,
      'palladio/json': renderJson,
      'palladio/agent-reference': renderAgentReference
    }
  },
  platforms: {
    css: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'css'),
      files: [{ destination: 'palladio.css', format: 'palladio/css' }]
    },
    typescript: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'ts'),
      files: [{ destination: 'tokens.ts', format: 'palladio/typescript' }]
    },
    json: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'json'),
      files: [{ destination: 'tokens.json', format: 'palladio/json' }]
    },
    agentReference: {
      transforms: ['name/palladio'],
      buildPath: `${distDir}${path.sep}`,
      files: [{ destination: 'agent-reference.md', format: 'palladio/agent-reference' }]
    }
  }
});

await styleDictionary.buildAllPlatforms();
console.log('Generated CSS, TypeScript, JSON and agent-reference.md artifacts with Style Dictionary.');
