import path from 'node:path';
import { fileURLToPath } from 'node:url';
import StyleDictionary from 'style-dictionary';
import { loadTokenSources } from './token-model.mjs';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const packageDir = path.resolve(__dirname, '..');
const distDir = path.join(packageDir, 'dist');

const { primitive, semantic, density, theme } = loadTokenSources(packageDir);

// Keep primitive tokens available to Style Dictionary for reference resolution,
// while putting each public token set under its artifact namespace.
const tokens = {
  ...primitive,
  semantic: semantic.pd,
  density: {
    compact: density.compact.pd,
    default: density.default.pd,
    spacious: density.spacious.pd
  },
  theme: { dark: theme.dark.pd }
};

function tokenValue(token) {
  return token['$value'];
}

function tokenType(token) {
  return token['$type'];
}

function transformCssValue(token) {
  const value = tokenValue(token);
  switch (tokenType(token)) {
    case 'color':
      return value.hex;
    case 'dimension':
    case 'duration':
      return `${value.value}${value.unit}`;
    case 'cubicBezier':
      return `cubic-bezier(${value.join(', ')})`;
    case 'fontWeight':
    case 'number':
      return String(value);
    case 'fontFamily':
      return value.join(', ');
    case 'typography':
      return [
        `${value.fontFamily.join(', ')}`,
        `${value.fontSize.value}${value.fontSize.unit}`,
        `font-weight ${value.fontWeight}`,
        `line-height ${value.lineHeight}`,
        `letter-spacing ${value.letterSpacing.value}${value.letterSpacing.unit}`
      ].join(' ');
    default:
      throw new Error(`Unsupported token type "${tokenType(token)}" at "${token.key}".`);
  }
}

function cssVariableName(token) {
  const pathStart = token.path[0] === 'semantic' ? 1 : 2;
  return `--pd-${token.path.slice(pathStart).join('-')}`;
}

function cssBlock(selector, records) {
  const lines = [`${selector} {`];
  for (const record of records) {
    lines.push(`  ${cssVariableName(record)}: ${transformCssValue(record)};`);
  }
  lines.push('}');
  return lines.join('\n');
}

function renderCss({ dictionary }) {
  const records = dictionary.allTokens;
  const semanticRecords = records.filter(
    (token) => token.path[0] === 'semantic' && token.path[1] !== 'color'
  );
  const themeRecords = records.filter(
    (token) => token.path[0] === 'theme' && token.path[1] === 'dark'
  );
  const densityRecords = (name) => records.filter(
    (token) => token.path[0] === 'density' && token.path[1] === name
  );

  return [
    '/* Generated by Palladio Style Dictionary pipeline. Do not edit. */',
    '',
    cssBlock(':root', semanticRecords),
    '',
    cssBlock(':root[data-theme="dark"]', themeRecords),
    '',
    cssBlock(':root[data-density]', densityRecords('default')),
    '',
    cssBlock(':root[data-density="compact"]', densityRecords('compact')),
    '',
    cssBlock(':root[data-density="spacious"]', densityRecords('spacious')),
    ''
  ].join('\n');
}

function nestedValues(records, stripSegments) {
  const result = {};
  for (const record of records) {
    const parts = record.path.slice(stripSegments);
    let current = result;
    for (const key of parts.slice(0, -1)) {
      if (!Object.hasOwn(current, key)) current[key] = {};
      current = current[key];
    }
    current[parts.at(-1)] = tokenValue(record);
  }
  return result;
}

function tokenSets(dictionary) {
  const records = dictionary.allTokens;
  const semanticRecords = records.filter((token) => token.path[0] === 'semantic');
  const densityRecords = (name) => records.filter(
    (token) => token.path[0] === 'density' && token.path[1] === name
  );
  const themeRecords = records.filter(
    (token) => token.path[0] === 'theme' && token.path[1] === 'dark'
  );

  return {
    semantic: nestedValues(semanticRecords, 1),
    density: {
      compact: nestedValues(densityRecords('compact'), 2),
      default: nestedValues(densityRecords('default'), 2),
      spacious: nestedValues(densityRecords('spacious'), 2)
    },
    theme: { dark: nestedValues(themeRecords, 2) }
  };
}

function stableStringify(value, indentation = 2) {
  if (Array.isArray(value)) {
    return `[${value.map((item) => stableStringify(item, indentation)).join(', ')}]`;
  }
  if (value && typeof value === 'object') {
    const entries = Object.entries(value);
    return entries.length === 0
      ? '{}'
      : `{
${entries.map(([key, item]) => `${' '.repeat(indentation)}${JSON.stringify(key)}: ${stableStringify(item, indentation + 2)}`).join(',\n')}
${' '.repeat(indentation - 2)}}`;
  }
  return JSON.stringify(value);
}

function renderTs({ dictionary }) {
  const { semantic, density, theme } = tokenSets(dictionary);
  return [
    '// Generated by Palladio Style Dictionary pipeline. Do not edit.',
    '',
    `export const palladioTokens = ${stableStringify(semantic)} as const;`,
    `export const palladioDensity = ${stableStringify(density)} as const;`,
    `export const palladioTheme = ${stableStringify(theme)} as const;`,
    '',
    'export type PalladioTokenValue =',
    '  | string',
    '  | number',
    '  | readonly string[]',
    '  | { readonly value: number; readonly unit: string }',
    '  | readonly [number, number, number, number];',
    ''
  ].join('\n');
}

function renderJson({ dictionary }) {
  return `${JSON.stringify(tokenSets(dictionary), null, 2)}\n`;
}

const styleDictionary = new StyleDictionary({
  tokens,
  hooks: {
    transforms: {
      'name/palladio': {
        type: 'name',
        transform: (token) => token.path.join('-')
      }
    },
    formats: {
      'palladio/css': renderCss,
      'palladio/typescript': renderTs,
      'palladio/json': renderJson
    }
  },
  platforms: {
    css: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'css'),
      files: [{ destination: 'palladio.css', format: 'palladio/css' }]
    },
    typescript: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'ts'),
      files: [{ destination: 'tokens.ts', format: 'palladio/typescript' }]
    },
    json: {
      transforms: ['name/palladio'],
      buildPath: path.join(distDir, 'json'),
      files: [{ destination: 'tokens.json', format: 'palladio/json' }]
    }
  }
});

await styleDictionary.buildAllPlatforms();
console.log('Generated CSS, TypeScript and JSON artifacts with Style Dictionary.');
