// Isolated comparison inputs. These override existing semantic roles for this
// executable review artifact only; they are not Palladio token proposals.
export const THEME_FIXTURES = {
  charcoal: {
    label: "深碳灰",
    description: "Dark, focused, architectural.",
    colors: {
      "--pd-color-bg": "#0c151c",
      "--pd-color-surface": "#111e27",
      "--pd-color-surface-raised": "#182832",
      "--pd-color-surface-overlay": "#20313c",
      "--pd-color-surface-hover": "#293c48",
      "--pd-color-border-subtle": "#2d3d47",
      "--pd-color-border-default": "#40515d",
      "--pd-color-border-strong": "#91a6b2",
      "--pd-color-input-border": "#91a6b2",
      "--pd-color-text-primary": "#f1f5f7",
      "--pd-color-text-secondary": "#b3c0c7",
      "--pd-color-text-placeholder": "#a9b7bf",
      "--pd-color-text-disabled": "#8d9aa1",
      "--pd-color-text-inverse": "#07131c",
      "--pd-color-accent": "#78aff5",
      "--pd-color-accent-hover": "#91bdf5",
      "--pd-color-accent-active": "#5f96dc",
      "--pd-color-accent-disabled": "#8999a3",
      "--pd-color-accent-subtle": "#223b4f",
      "--pd-color-accent-text": "#07131c",
    },
  },
  metal: {
    label: "金屬灰",
    description: "Deeper metal, balanced and quiet.",
    colors: {
      "--pd-color-bg": "#30383e",
      "--pd-color-surface": "#394249",
      "--pd-color-surface-raised": "#434d55",
      "--pd-color-surface-overlay": "#4d5861",
      "--pd-color-surface-hover": "#56626c",
      "--pd-color-border-subtle": "#515d66",
      "--pd-color-border-default": "#65717a",
      "--pd-color-border-strong": "#c1cbd1",
      "--pd-color-input-border": "#c1cbd1",
      "--pd-color-text-primary": "#ffffff",
      "--pd-color-text-secondary": "#e0e5e8",
      "--pd-color-text-placeholder": "#d6dde1",
      "--pd-color-text-disabled": "#c3cbd0",
      "--pd-color-text-inverse": "#10171d",
      "--pd-color-accent": "#a9caf3",
      "--pd-color-accent-hover": "#bdd8f8",
      "--pd-color-accent-active": "#91b7e7",
      "--pd-color-accent-disabled": "#aebcc5",
      "--pd-color-accent-subtle": "#465d70",
      "--pd-color-accent-text": "#10171d",
    },
  },
  moon: {
    label: "月牙白",
    description: "Clean, warm and open.",
    colors: {
      "--pd-color-bg": "#f1efe9",
      "--pd-color-surface": "#faf9f5",
      "--pd-color-surface-raised": "#ece9e2",
      "--pd-color-surface-overlay": "#e2ded5",
      "--pd-color-surface-hover": "#dedbd4",
      "--pd-color-border-subtle": "#d3cfc6",
      "--pd-color-border-default": "#b8b4ac",
      "--pd-color-border-strong": "#596773",
      "--pd-color-input-border": "#596773",
      "--pd-color-text-primary": "#17212a",
      "--pd-color-text-secondary": "#52606b",
      "--pd-color-text-placeholder": "#46525c",
      "--pd-color-text-disabled": "#727b82",
      "--pd-color-text-inverse": "#ffffff",
      "--pd-color-accent": "#1764c0",
      "--pd-color-accent-hover": "#0c55aa",
      "--pd-color-accent-active": "#08458e",
      "--pd-color-accent-disabled": "#5d6b77",
      "--pd-color-accent-subtle": "#d8e6f7",
      "--pd-color-accent-text": "#ffffff",
    },
  },
};

export function themeStyle(theme) {
  return THEME_FIXTURES[theme].colors;
}
